### ISSUE TITLE
Settings menu crashes on opening

### ISSUE THREAD

**Issue by Dykam** [Dykam/tabbychat#23]
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 19-2-14 17:09
Description: Updating screen events

java.lang.IncompatibleClassChangeError: Expected static field acs.tabbychat.gui.TCSettingsGeneral.field_146297_k
    at acs.tabbychat.gui.TCSettingsGeneral.initDrawableSettings(TCSettingsGeneral.java:110)
    at acs.tabbychat.gui.TCSettingsGUI.func_73866_w_(TCSettingsGUI.java:147)
    at acs.tabbychat.gui.TCSettingsGeneral.func_73866_w_(TCSettingsGeneral.java:21)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:262)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:779)
    at acs.tabbychat.core.GuiChatTC.func_146284_a(GuiChatTC.java:75)
    at acs.tabbychat.core.GuiChatTC.func_73864_a(GuiChatTC.java:617)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:309)
    at net.minecraft.client.gui.GuiChat.func_146274_d(GuiChat.java:151)
    at acs.tabbychat.core.GuiChatTC.func_146274_d(GuiChatTC.java:358)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:275)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1625)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:953)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:870)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at acs.tabbychat.gui.TCSettingsGeneral.initDrawableSettings(TCSettingsGeneral.java:110)
    at acs.tabbychat.gui.TCSettingsGUI.func_73866_w_(TCSettingsGUI.java:147)
    at acs.tabbychat.gui.TCSettingsGeneral.func_73866_w_(TCSettingsGeneral.java:21)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:262)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:779)
    at acs.tabbychat.core.GuiChatTC.func_146284_a(GuiChatTC.java:75)
    at acs.tabbychat.core.GuiChatTC.func_73864_a(GuiChatTC.java:617)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:309)
    at net.minecraft.client.gui.GuiChat.func_146274_d(GuiChat.java:151)
    at acs.tabbychat.core.GuiChatTC.func_146274_d(GuiChatTC.java:358)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:275)

-- Affected screen --
Details:
    Screen name: acs.tabbychat.gui.TCSettingsGeneral

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Dykam'/61, l='MpServer', x=133,22, y=66,11, z=248,10]]
    Chunk stats: MultiplayerChunkCache: 225, 225
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1075,4,-418), Chunk: (at 3,0,14 in 67,-27; contains blocks 1072,0,-432 to 1087,255,-417), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
    Level time: 85934789 game time, 13445000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['Dykam'/61, l='MpServer', x=133,22, y=66,11, z=248,10]]
    Retry entities: 0 total; []
    Server brand: CraftBukkit
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:384)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:891)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0-ea, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 68266024 bytes (65 MB) / 517472256 bytes (493 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 57679 (3230024 bytes; 3 MB) allocated, 2 (112 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.116.1024 Minecraft Forge 10.12.0.1024 5 mods loaded, 5 mods active
    mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.2.116.1024} [Forge Mod Loader] (forge-1.7.2-10.12.0.1024.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.12.0.1024} [Minecraft Forge] (forge-1.7.2-10.12.0.1024.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    tabbychat{1.11.00} [TabbyChat] (TabbyChat-1.11.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    UndercastMod{1.7.6} [UndercastMod] (UndercastMod-1.7.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Launched Version: 1.7.2-Forge10.12.0.1024
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 680/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 100 (5600 bytes; 0 MB) allocated, 22 (1232 bytes; 0 MB) used
    Anisotropic Filtering: On (16)
```

**Comment by mattmess1221** [comment]
I can't reproduce it. Does it only happen when obfuscated? It would appear so.

**Comment by Dykam** [comment]
Yes, using Forge #1024. I have an idea why it happens, I'll look into it later. It might happen with the reobfuscation, where a field gets renamed which shouldn't.

Btw, how is your setup to test unobfuscated? Does it use forgegradle or just something custom?

**Comment by mattmess1221** [comment]
I use Eclipse to run the deobfuscated code. Using gradle, you can run use it to set up your eclipse environment. MCP does this automatically.  Point eclipse to the eclipse folder as your workspace.

**Comment by Dykam** [comment]
This seems to happen in all menu's. I'll have to look into a proper solution, something is causing `TCSettingsGUI` not to compile properly

**Comment by Dykam** [comment]
Regarding running it, I'm using IntelliJ. With LiteLoader it is easy, it includes a mini-launcher to keep the session up to date. Is there a way to do the same with forge, or do you run it in offline-mode (how)

**Comment by mattmess1221** [comment]
Run "gradlew idea" then point IntelliJ to eclipse.  It will set everything up for you.

**Comment by Dykam** [comment]
It's missing launchwrapper. Which for some reason doesn't get included after I added it as source. I'll look into that tomorrow..

**Comment by mattmess1221** [comment]
Its best to create a new issue about this.

**Comment by Dykam** [comment]
It isn't a tabbychat issue, just my local setup. I'll clean up this discussion once I fix it.
